# Generated by Django 4.1.1 on 2022-10-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumsOrders',
            fields=[
                ('album_order_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'album_order',
                'managed': False,
            },
        ),
    ]
